export const LOADER_START = 'LOADER_START';
export const LOADER_STOP = 'LOADER_STOP';

export const GET_REPO_START = 'GET_REPO_START';
export const GET_REPO_SUCCESS = 'GET_REPO_SUCCESS';
export const GET_REPO_FAIL = 'GET_REPO_FAIL';

export const GET_FOLLOWERS_START = 'GET_FOLLOWERS_START';
export const GET_FOLLOWERS_SUCCESS = 'GET_FOLLOWERS_SUCCESS';
export const GET_FOLLOWERS_FAIL = 'GET_FOLLOWERS_FAIL';
